# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-18 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=5)),
                ('manufacture', models.CharField(max_length=4)),
                ('description', models.CharField(max_length=500)),
                ('height', models.CharField(max_length=4)),
                ('width', models.CharField(max_length=4)),
                ('depth', models.CharField(max_length=4)),
            ],
        ),
    ]
